language: node_js
node_js:
  - '6'
  - 'node'
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script:
      - 'yarn run tslint'
      - 'yarn run prettier'
      - 'yarn run test'
    - stage: deploy
      node_js: '6'
      script:
      - 'yarn install --prod'
      deploy:
        provider: npm
        email: nenadalm@gmail.com
        api_key:
          secure: "AkY5yy2VhGSwbxcRUTd3Urg0AOVcIgeQ+YcOd0Vx1MdseOBMEVkb01K9P8lmWM+LFOipouut0b1mQpLhm7i7et4DFTDucnhAQTzlrEc7oXD54tARLuGUZtAmuM2jGkEWc9kzjiteAsj7TNKPvnOEtJtmqEzqHw5+603yyL5fKIwcqfXagwSeBVTDXChFRA92Z2A7/No1aI1oTyXVeBQiton1iY3llsuuvirIMv4BZTcninmgPER0KBWIjqpiXXQnDDz7WkdL2ywaS6tR5ZrfAwz4HmWS8Rxx1PlcXlrnfHqbDmdgIxC4aJ3YPU4M0500KZw5todeReU0wo3IehSIwBQw+8T+sJGTZqhYabZHfLrv3IvckQB0UdCazGoIxsg7Rtkm6zvozjmHDlpTUcANT5imTJGkfHTq68dS61H+7MRVZ8dQ61KGXvNB3XEgQY0l+8d9wETlVMyy907JU62OagV/hEdyxrG5Jq62uybdmUvxqENtmw7+2OaESAqLNTibWO0/ccYb3I2YSglLQWGMR0KZBulCRbjnvaww02qA8RB0xfPUKKOk0Edo8am5RsY+oSrcHjbgrcY6TMed2RM5n6ULB1hxbw5eHZ3k3DG8Qq4EqPt4mfIThcA7TuvXkGvM85UjaCB+Wgjc3WmdyDcxuLUQ3OR1Ej44E2X0sYMftfw="
        on:
          tags: true
          repo: imatic/pgqb
          branch: master
