on: [push]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - run: 'yarn install'
            - run: 'yarn run tslint'
            - run: 'yarn run prettier'
            - run: 'yarn run test'
    release:
        needs: test
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12'
                  registry-url: 'https://registry.npmjs.org'
            - run: 'yarn install --prod'
            - run: 'yarn publish'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
